// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package blada_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ID请求
type IdRequest struct {
	// ID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// IDS请求
type IdsRequest struct {
	// ID
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsRequest) Reset()         { *m = IdsRequest{} }
func (m *IdsRequest) String() string { return proto.CompactTextString(m) }
func (*IdsRequest) ProtoMessage()    {}
func (*IdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *IdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsRequest.Unmarshal(m, b)
}
func (m *IdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsRequest.Marshal(b, m, deterministic)
}
func (m *IdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsRequest.Merge(m, src)
}
func (m *IdsRequest) XXX_Size() int {
	return xxx_messageInfo_IdsRequest.Size(m)
}
func (m *IdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdsRequest proto.InternalMessageInfo

func (m *IdsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// 结果状态
// 如果code!=0,则为失败
type ResultState struct {
	// 所属服务
	Service int32 `protobuf:"varint,1,opt,name=service,proto3" json:"service,omitempty"`
	// 错误码
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// 错误消息
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultState) Reset()         { *m = ResultState{} }
func (m *ResultState) String() string { return proto.CompactTextString(m) }
func (*ResultState) ProtoMessage()    {}
func (*ResultState) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *ResultState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultState.Unmarshal(m, b)
}
func (m *ResultState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultState.Marshal(b, m, deterministic)
}
func (m *ResultState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultState.Merge(m, src)
}
func (m *ResultState) XXX_Size() int {
	return xxx_messageInfo_ResultState.Size(m)
}
func (m *ResultState) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultState.DiscardUnknown(m)
}

var xxx_messageInfo_ResultState proto.InternalMessageInfo

func (m *ResultState) GetService() int32 {
	if m != nil {
		return m.Service
	}
	return 0
}

func (m *ResultState) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResultState) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 通用模型
type Model struct {
	// 主键
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreateTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 修改时间
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// 是否删除
	SoftDelete           bool     `protobuf:"varint,4,opt,name=softDelete,proto3" json:"softDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Model) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Model) GetSoftDelete() bool {
	if m != nil {
		return m.SoftDelete
	}
	return false
}

// 分页请求
type PageRequest struct {
	// 查询页码
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 查询数量
	Rows                 int64    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetRows() int64 {
	if m != nil {
		return m.Rows
	}
	return 0
}

// 分页结果
type PageResult struct {
	// 总数
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageResult) Reset()         { *m = PageResult{} }
func (m *PageResult) String() string { return proto.CompactTextString(m) }
func (*PageResult) ProtoMessage()    {}
func (*PageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *PageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResult.Unmarshal(m, b)
}
func (m *PageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResult.Marshal(b, m, deterministic)
}
func (m *PageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResult.Merge(m, src)
}
func (m *PageResult) XXX_Size() int {
	return xxx_messageInfo_PageResult.Size(m)
}
func (m *PageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResult.DiscardUnknown(m)
}

var xxx_messageInfo_PageResult proto.InternalMessageInfo

func (m *PageResult) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*IdRequest)(nil), "iok200.common.IdRequest")
	proto.RegisterType((*IdsRequest)(nil), "iok200.common.IdsRequest")
	proto.RegisterType((*ResultState)(nil), "iok200.common.ResultState")
	proto.RegisterType((*Model)(nil), "iok200.common.Model")
	proto.RegisterType((*PageRequest)(nil), "iok200.common.PageRequest")
	proto.RegisterType((*PageResult)(nil), "iok200.common.PageResult")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x31, 0x4f, 0xf3, 0x30,
	0x14, 0x54, 0x9a, 0xf6, 0xfb, 0xe8, 0x2b, 0x20, 0x64, 0x31, 0x44, 0x45, 0x2a, 0x91, 0xa7, 0x2e,
	0x24, 0x55, 0x11, 0x0b, 0x23, 0x62, 0xe9, 0x80, 0x84, 0x4c, 0x59, 0xd8, 0x9c, 0xf8, 0x35, 0x58,
	0x24, 0x38, 0xc4, 0x2f, 0xf0, 0xb3, 0xf8, 0x8b, 0xc8, 0x36, 0x11, 0x15, 0x0b, 0x4b, 0x74, 0xef,
	0x7c, 0xe7, 0xdc, 0xf9, 0xc1, 0x61, 0x69, 0x9a, 0xc6, 0xbc, 0x66, 0x6d, 0x67, 0xc8, 0xb0, 0x23,
	0x6d, 0x5e, 0xd6, 0xab, 0x55, 0x16, 0xc8, 0xf9, 0x79, 0x65, 0x4c, 0x55, 0x63, 0xee, 0x0f, 0x8b,
	0x7e, 0x97, 0x93, 0x6e, 0xd0, 0x92, 0x6c, 0xda, 0xa0, 0xe7, 0x67, 0x30, 0xdd, 0x28, 0x81, 0x6f,
	0x3d, 0x5a, 0x62, 0xc7, 0x30, 0xd2, 0x2a, 0x89, 0xd2, 0x68, 0x39, 0x15, 0x23, 0xad, 0xf8, 0x02,
	0x60, 0xa3, 0xec, 0x70, 0x7a, 0x02, 0xb1, 0x56, 0x36, 0x89, 0xd2, 0x78, 0x39, 0x15, 0x0e, 0xf2,
	0x47, 0x98, 0x09, 0xb4, 0x7d, 0x4d, 0x0f, 0x24, 0x09, 0x59, 0x02, 0xff, 0x2d, 0x76, 0xef, 0xba,
	0x44, 0x7f, 0xc7, 0x44, 0x0c, 0x23, 0x63, 0x30, 0x2e, 0x8d, 0xc2, 0x64, 0xe4, 0x69, 0x8f, 0x9d,
	0xba, 0x41, 0x6b, 0x65, 0x85, 0x49, 0xec, 0xff, 0x38, 0x8c, 0xfc, 0x33, 0x82, 0xc9, 0x9d, 0x51,
	0x58, 0xff, 0x0e, 0xc4, 0xae, 0x01, 0xca, 0x0e, 0x25, 0xe1, 0x56, 0x37, 0xe1, 0xb6, 0xd9, 0x7a,
	0x9e, 0x85, 0x8e, 0xd9, 0xd0, 0x31, 0xdb, 0x0e, 0x1d, 0xc5, 0x9e, 0xda, 0x79, 0xfb, 0x56, 0x0d,
	0xde, 0xf8, 0x6f, 0xef, 0x8f, 0x9a, 0x2d, 0x00, 0xac, 0xd9, 0xd1, 0x2d, 0xd6, 0x48, 0x98, 0x8c,
	0xd3, 0x68, 0x79, 0x20, 0xf6, 0x18, 0x7e, 0x05, 0xb3, 0x7b, 0x59, 0xe1, 0xf0, 0x52, 0x0c, 0xc6,
	0xad, 0xeb, 0xe5, 0x82, 0xc7, 0xc2, 0x63, 0xc7, 0x75, 0xe6, 0xc3, 0xfa, 0xd0, 0xb1, 0xf0, 0x98,
	0x73, 0x80, 0x60, 0x73, 0x6f, 0xc8, 0x4e, 0x61, 0x42, 0x86, 0x64, 0xfd, 0x6d, 0x0b, 0xc3, 0x0d,
	0x7f, 0x4a, 0x2b, 0x4d, 0xcf, 0x7d, 0xe1, 0x56, 0x9a, 0x87, 0xed, 0xe6, 0x45, 0x2d, 0x95, 0x0c,
	0xdf, 0x8b, 0xb6, 0x28, 0xfe, 0xf9, 0xf8, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xeb,
	0x8c, 0x3c, 0x0b, 0x02, 0x00, 0x00,
}
